name: Publish image to Docker Hub
on: 
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_KEY }}" | docker login -u "atmajo" --password-stdin
      
      - name: Build Docker image
        run: docker build . -t atmajo/streamapp-app:latest

      - name: Push Docker image
        run: docker push atmajo/streamapp-app:latest
