name: Publish image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t atmajo/streamapp-app:latest

      - name: Push Docker image
        run: |
          docker login -u atmajo -p ${{ sectrets.DOCKER_HUB_KEY }}
          docker push atmajo/streamapp-app:latest
